### ISSUE TITLE
Does it work for a Free Zapier plan?

### ISSUE THREAD

**Issue by diger74** [kentico-ericd/xperience-zapier-cli#1]
Does it work for a Free Zapier plan? Or it requires Starter at least?
![image](https://user-images.githubusercontent.com/1597268/97059935-d305af00-1589-11eb-8a98-ef5dd41ed552.png)

**Comment by kentico-ericd** [comment]
Hey @diger74, thanks for the interest in the integration :)

It **does** work with the Free plan. The "Connections via webhooks" note that you see in the Starter plan is a reference to Zapier's **Catch Hook** trigger which requires a paid plan (this is the trigger that is mentioned [here](https://github.com/kentico-ericd/xperience-zapier-cli#using-the-integration-without-nuget-packages)). But, if you've installed the NuGet packages and you're using the native **Catch Xperience Webhook** trigger, you don't need a paid plan.

The major drawback of the Free plan is the single-step Zap.. it's quite limiting :/

**Comment by kentico-ericd** [comment]
As a followup, this is a good note for the readme, so I'll add it to the topmost section :)
